In [2]:
    #1
# Import the necessary library
import numpy as np

# Create an array containing the values 1–15
array = np.arange(1, 16)

# Reshape the array into a 3-by-5 array
array = array.reshape(3, 5)
print("3-by-5 Array:")
print(array)

# a) Select row 2
row_2 = array[2]
print("\nRow 2:")
print(row_2)

# b) Select column 5 (note: Python uses 0-based indexing, so column 5 is index 4)
column_5 = array[:, 4]
print("\nColumn 5:")
print(column_5)

# c) Select rows 0 and 1
rows_0_and_1 = array[0:2]
print("\nRows 0 and 1:")
print(rows_0_and_1)

# d) Select columns 2–4
columns_2_to_4 = array[:, 2:5]
print("\nColumns 2 to 4:")
print(columns_2_to_4)

# e) Select the element that is in row 1 and column 4
element_row_1_col_4 = array[1, 4]
print("\nElement in row 1 and column 4:")
print(element_row_1_col_4)

# f) Select all elements from rows 1 and 2 that are in columns 0, 2, and 4
elements_rows_1_and_2_cols_0_2_4 = array[1:3, [0, 2, 4]]
print("\nElements from rows 1 and 2 in columns 0, 2, and 4:")
print(elements_rows_1_and_2_cols_0_2_4)


3-by-5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Row 2:
[11 12 13 14 15]

Column 5:
[ 5 10 15]

Rows 0 and 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Columns 2 to 4:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]

Element in row 1 and column 4:
10

Elements from rows 1 and 2 in columns 0, 2, and 4:
[[ 6  8 10]
 [11 13 15]]


In [3]:
    #2

# Import the necessary library
import numpy as np

# Task 1: Indexing and Slicing arrays
# Create an array containing the values 1–15
array = np.arange(1, 16)

# Reshape the array into a 3-by-5 array
array = array.reshape(3, 5)
print("3-by-5 Array:")
print(array)

# a) Select row 2
row_2 = array[2]
print("\nRow 2:")
print(row_2)

# b) Select column 5 (note: Python uses 0-based indexing, so column 5 is index 4)
column_5 = array[:, 4]
print("\nColumn 5:")
print(column_5)

# c) Select rows 0 and 1
rows_0_and_1 = array[0:2]
print("\nRows 0 and 1:")
print(rows_0_and_1)

# d) Select columns 2–4
columns_2_to_4 = array[:, 2:5]
print("\nColumns 2 to 4:")
print(columns_2_to_4)

# e) Select the element that is in row 1 and column 4
element_row_1_col_4 = array[1, 4]
print("\nElement in row 1 and column 4:")
print(element_row_1_col_4)

# f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4
elements_rows_1_and_2_cols_0_2_4 = array[1:3, [0, 2, 4]]
print("\nElements from rows 1 and 2 in columns 0, 2, and 4:")
print(elements_rows_1_and_2_cols_0_2_4)

# Task 2: Filling arrays
# Fill a 2-by-3 array with ones
array_ones = np.ones((2, 3))
print("\n2-by-3 Array filled with ones:")
print(array_ones)

# Fill a 3-by-3 array with zeros
array_zeros = np.zeros((3, 3))
print("\n3-by-3 Array filled with zeros:")
print(array_zeros)

# Fill a 2-by-5 array with 7s
array_sevens = np.full((2, 5), 7)
print("\n2-by-5 Array filled with 7s:")
print(array_sevens)


3-by-5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Row 2:
[11 12 13 14 15]

Column 5:
[ 5 10 15]

Rows 0 and 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Columns 2 to 4:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]

Element in row 1 and column 4:
10

Elements from rows 1 and 2 in columns 0, 2, and 4:
[[ 6  8 10]
 [11 13 15]]

2-by-3 Array filled with ones:
[[1. 1. 1.]
 [1. 1. 1.]]

3-by-3 Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2-by-5 Array filled with 7s:
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [4]:
#3
# Import the necessary library
import numpy as np

# Create a 2-by-2 array containing the numbers 0–3
array = np.arange(4).reshape(2, 2)
print("Original 2-by-2 Array:")
print(array)

# a) Cube every element of the array
array_cubed = array ** 3
print("\nCubed Array:")
print(array_cubed)

# b) Add 7 to every element of the array
array_plus_7 = array + 7
print("\nArray with 7 Added to Each Element:")
print(array_plus_7)

# c) Multiply every element of the array by 2
array_times_2 = array * 2
print("\nArray with Each Element Multiplied by 2:")
print(array_times_2)


Original 2-by-2 Array:
[[0 1]
 [2 3]]

Cubed Array:
[[ 0  1]
 [ 8 27]]

Array with 7 Added to Each Element:
[[ 7  8]
 [ 9 10]]

Array with Each Element Multiplied by 2:
[[0 2]
 [4 6]]


In [1]:
# 4
# Import the necessary library
import numpy as np

# Given arrays
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# a) Use vertical stacking to create array3 (4-by-2) with array1 stacked on top of array2
array3 = np.vstack((array1, array2))
print("Array3 (Vertical stacking of array1 and array2):")
print(array3)

# b) Use horizontal stacking to create array4 (2-by-4) with array2 to the right of array1
array4 = np.hstack((array1, array2))
print("\nArray4 (Horizontal stacking of array1 and array2):")
print(array4)

# c) Use vertical stacking with two copies of array4 to create array5 (4-by-4)
array5 = np.vstack((array4, array4))
print("\nArray5 (Vertical stacking of two copies of array4):")
print(array5)

# d) Use horizontal stacking with two copies of array3 to create array6 (4-by-4)
array6 = np.hstack((array3, array3))
print("\nArray6 (Horizontal stacking of two copies of array3):")
print(array6)


Array3 (Vertical stacking of array1 and array2):
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Array4 (Horizontal stacking of array1 and array2):
[[0 1 4 5]
 [2 3 6 7]]

Array5 (Vertical stacking of two copies of array4):
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

Array6 (Horizontal stacking of two copies of array3):
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [2]:
# 5
# Import the necessary library
import numpy as np

# Create the first array with even integers from 2 to 18
array1 = np.arange(2, 20, 2).reshape(3, 3)
print("First Array (Even integers from 2 to 18):")
print(array1)

# Create the second array with integers from 9 down to 1
array2 = np.arange(9, 0, -1).reshape(3, 3)
print("\nSecond Array (Integers from 9 down to 1):")
print(array2)

# Multiply the first array by the second array element-wise
result_array = array1 * array2
print("\nElement-wise multiplication of array1 and array2:")
print(result_array)


First Array (Even integers from 2 to 18):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Second Array (Integers from 9 down to 1):
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise multiplication of array1 and array2:
[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [4]:
import numpy as np

def initialize_board():
    """
    Initialize the 3x3 Tic-Tac-Toe board with empty strings.

    Returns:
    np.ndarray: A 3x3 NumPy array filled with empty strings ('').
    """
    return np.full((3, 3), '', dtype=str)

def display_board(board):
    """
    Display the current state of the Tic-Tac-Toe board.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    """
    print("\nCurrent Board:")
    print(board)

def check_winner(board, player):
    """
    Check if the specified player has won the game.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    player (str): The player's mark ('X' or 'O') to check for winning condition.

    Returns:
    bool: True if the player has won, False otherwise.
    """
    # Check rows and columns for three consecutive marks
    for i in range(3):
        if all(board[i, :] == player) or all(board[:, i] == player):
            return True

    # Check diagonals
    if all(np.diag(board) == player) or all(np.diag(np.fliplr(board)) == player):
        return True

    return False

def check_draw(board):
    """
    Check if the game is a draw (all squares filled).

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.

    Returns:
    bool: True if the game is a draw, False otherwise.
    """
    return '' not in board

def check_game_state(board):
    """
    Check the current state of the Tic-Tac-Toe game.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.

    Returns:
    str: Message indicating current game state:
         - "Player 'X' is winning!" if 'X' has won.
         - "Player 'O' is winning!" if 'O' has won.
         - "It's a draw!" if the game is a draw.
         - "Game in progress..." if no winner and no draw yet.
    """
    if check_winner(board, 'X'):
        return "Player 'X' is winning!"
    elif check_winner(board, 'O'):
        return "Player 'O' is winning!"
    elif check_draw(board):
        return "It's a draw!"
    else:
        return "Game in progress..."

def get_player_move(board, player):
    """
    Get the player's move (row and column indices).

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    player (str): The current player's mark ('X' or 'O').

    Returns:
    tuple: The row and column indices chosen by the player.
    """
    while True:
        try:
            row = int(input(f"\nPlayer '{player}', enter the row index (0, 1, or 2): "))
            col = int(input(f"Player '{player}', enter the column index (0, 1, or 2): "))

            if 0 <= row <= 2 and 0 <= col <= 2:
                if board[row, col] == '':
                    return row, col
                else:
                    print("That square is already taken. Try again.")
            else:
                print("Row and column indices must be between 0 and 2. Try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")

def main():
    """
    Main function to play the Tic-Tac-Toe game between two human players.
    """
    board = initialize_board()  # Initialize the game board
    current_player = 'X'  # Player 1 starts with 'X'

    while True:
        display_board(board)  # Display current board state

        # Get player's move
        row, col = get_player_move(board, current_player)
        board[row, col] = current_player

        # Check the current game state
        game_state = check_game_state(board)
        if game_state != "Game in progress...":
            display_board(board)
            print(f"\n{game_state}")
            break

        # Switch to the other player
        current_player = 'O' if current_player == 'X' else 'X'

if __name__ == "__main__":
    main()



Current Board:
[['' '' '']
 ['' '' '']
 ['' '' '']]

Player 'X', enter the row index (0, 1, or 2): the Tic-Tac-Toe game
Invalid input. Please enter a number.

Player 'X', enter the row index (0, 1, or 2): 0
Player 'X', enter the column index (0, 1, or 2): 1

Current Board:
[['' 'X' '']
 ['' '' '']
 ['' '' '']]

Player 'O', enter the row index (0, 1, or 2): 2
Player 'O', enter the column index (0, 1, or 2): 0

Current Board:
[['' 'X' '']
 ['' '' '']
 ['O' '' '']]

Player 'X', enter the row index (0, 1, or 2): 0
Player 'X', enter the column index (0, 1, or 2): 1
That square is already taken. Try again.

Player 'X', enter the row index (0, 1, or 2): 2
Player 'X', enter the column index (0, 1, or 2): 1

Current Board:
[['' 'X' '']
 ['' '' '']
 ['O' 'X' '']]

Player 'O', enter the row index (0, 1, or 2): 0
Player 'O', enter the column index (0, 1, or 2): 1
That square is already taken. Try again.

Player 'O', enter the row index (0, 1, or 2): 2
Player 'O', enter the column index (0, 1, or 

In [5]:
#7
import numpy as np
import random

def initialize_board():
    """
    Initialize the 3x3 Tic-Tac-Toe board with empty strings.

    Returns:
    np.ndarray: A 3x3 NumPy array filled with empty strings ('').
    """
    return np.full((3, 3), '', dtype=str)

def display_board(board):
    """
    Display the current state of the Tic-Tac-Toe board.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    """
    print("\nCurrent Board:")
    print(board)

def check_winner(board, player):
    """
    Check if the specified player has won the game.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    player (str): The player's mark ('X' or 'O') to check for winning condition.

    Returns:
    bool: True if the player has won, False otherwise.
    """
    # Check rows and columns for three consecutive marks
    for i in range(3):
        if all(board[i, :] == player) or all(board[:, i] == player):
            return True

    # Check diagonals
    if all(np.diag(board) == player) or all(np.diag(np.fliplr(board)) == player):
        return True

    return False

def check_draw(board):
    """
    Check if the game is a draw (all squares filled).

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.

    Returns:
    bool: True if the game is a draw, False otherwise.
    """
    return '' not in board

def check_game_state(board):
    """
    Check the current state of the Tic-Tac-Toe game.

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.

    Returns:
    str: Message indicating current game state:
         - "Player 'X' is winning!" if 'X' has won.
         - "Player 'O' is winning!" if 'O' has won.
         - "It's a draw!" if the game is a draw.
         - "Game in progress..." if no winner and no draw yet.
    """
    if check_winner(board, 'X'):
        return "Player 'X' is winning!"
    elif check_winner(board, 'O'):
        return "Player 'O' is winning!"
    elif check_draw(board):
        return "It's a draw!"
    else:
        return "Game in progress..."

def get_player_move(board, player):
    """
    Get the player's move (row and column indices).

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    player (str): The current player's mark ('X' or 'O').

    Returns:
    tuple: The row and column indices chosen by the player.
    """
    while True:
        try:
            row = int(input(f"\nPlayer '{player}', enter the row index (0, 1, or 2): "))
            col = int(input(f"Player '{player}', enter the column index (0, 1, or 2): "))

            if 0 <= row <= 2 and 0 <= col <= 2:
                if board[row, col] == '':
                    return row, col
                else:
                    print("That square is already taken. Try again.")
            else:
                print("Row and column indices must be between 0 and 2. Try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")

def get_computer_move(board, computer):
    """
    Get the computer's move (random selection of an empty cell).

    Args:
    board (np.ndarray): The 3x3 NumPy array representing the game board.
    computer (str): The computer's mark ('X' or 'O').

    Returns:
    tuple: The row and column indices chosen by the computer.
    """
    empty_cells = np.where(board == '')
    idx = random.choice(range(len(empty_cells[0])))
    row = empty_cells[0][idx]
    col = empty_cells[1][idx]
    return row, col

def main():
    """
    Main function to play the Tic-Tac-Toe game between a human player and the computer.
    """
    board = initialize_board()  # Initialize the game board

    # Determine player and computer marks
    player_choice = input("Do you want to be 'X' or 'O'? ").upper()
    computer_choice = 'X' if player_choice == 'O' else 'O'

    current_player = 'X'  # Player 1 starts with 'X'

    # Decide who starts first
    if player_choice == 'O':
        print("Player 'O' goes first.")
    else:
        print("You ('X') go first.")

    while True:
        display_board(board)  # Display current board state

        # Human player's move
        if current_player == player_choice:
            row, col = get_player_move(board, current_player)
        # Computer's move
        else:
            row, col = get_computer_move(board, current_player)
            print(f"\nComputer ({current_player}) chooses row {row} and column {col}.")

        # Make the move on the board
        board[row, col] = current_player

        # Check the current game state
        game_state = check_game_state(board)
        if game_state != "Game in progress...":
            display_board(board)
            print(f"\n{game_state}")
            break

        # Switch to the other player
        current_player = 'O' if current_player == 'X' else 'X'

if __name__ == "__main__":
    main()


Do you want to be 'X' or 'O'? x
You ('X') go first.

Current Board:
[['' '' '']
 ['' '' '']
 ['' '' '']]

Player 'X', enter the row index (0, 1, or 2): 0
Player 'X', enter the column index (0, 1, or 2): 1

Current Board:
[['' 'X' '']
 ['' '' '']
 ['' '' '']]

Computer (O) chooses row 0 and column 0.

Current Board:
[['O' 'X' '']
 ['' '' '']
 ['' '' '']]

Player 'X', enter the row index (0, 1, or 2): 1
Player 'X', enter the column index (0, 1, or 2): 2

Current Board:
[['O' 'X' '']
 ['' '' 'X']
 ['' '' '']]

Computer (O) chooses row 1 and column 1.

Current Board:
[['O' 'X' '']
 ['' 'O' 'X']
 ['' '' '']]

Player 'X', enter the row index (0, 1, or 2): 0
Player 'X', enter the column index (0, 1, or 2): 1
That square is already taken. Try again.

Player 'X', enter the row index (0, 1, or 2): 1
Player 'X', enter the column index (0, 1, or 2): 0

Current Board:
[['O' 'X' '']
 ['X' 'O' 'X']
 ['' '' '']]

Computer (O) chooses row 2 and column 1.

Current Board:
[['O' 'X' '']
 ['X' 'O' 'X']
 ['

In [6]:
#8
import pandas as pd
import numpy as np

# a) Create a Series from the list [7, 11, 13, 17].
series_a = pd.Series([7, 11, 13, 17])
print("Series (a):")
print(series_a)
print()

# b) Create a Series with five elements that are all 100.0.
series_b = pd.Series(100.0, index=range(5))
print("Series (b):")
print(series_b)
print()

# c) Create a Series with 20 elements that are all random numbers in the range 0 to 100.
np.random.seed(0)  # For reproducibility
series_c = pd.Series(np.random.randint(0, 101, 20))
print("Series (c):")
print(series_c.describe())
print()

# d) Create a Series called temperatures with custom indices 'Julie', 'Charlie', 'Sam', and 'Andrea'.
temperatures = pd.Series([98.6, 98.9, 100.2, 97.9], index=['Julie', 'Charlie', 'Sam', 'Andrea'])
print("Series (d):")
print(temperatures)
print()

# e) Form a dictionary from the names and values in Part (d), then use it to initialize a Series.
temp_dict = {'Julie': 98.6, 'Charlie': 98.9, 'Sam': 100.2, 'Andrea': 97.9}
series_e = pd.Series(temp_dict)
print("Series (e):")
print(series_e)


Series (a):
0     7
1    11
2    13
3    17
dtype: int64

Series (b):
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64

Series (c):
count    20.000000
mean     58.300000
std      25.739791
min       9.000000
25%      42.750000
50%      64.500000
75%      84.000000
max      88.000000
dtype: float64

Series (d):
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64

Series (e):
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64
